# Multinimial Naive Bayes Classification

In [32]:
import pandas as pd
import numpy as np

In [33]:
df=pd.read_csv('/content/drive/MyDrive/datasets/ml/SMSSpamCollection',sep='\t',names=['status','msg'])
df

status                                                msg
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham               Will ü b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [34]:
df.shape

(5572, 2)

In [35]:
df.status.value_counts()

status
ham     4825
spam     747
Name: count, dtype: int64

In [36]:
df.loc[df['status']=='spam','status']=0
df.loc[df['status']=='ham','status']=1
df

status                                                msg
0         1  Go until jurong point, crazy.. Available only ...
1         1                      Ok lar... Joking wif u oni...
2         0  Free entry in 2 a wkly comp to win FA Cup fina...
3         1  U dun say so early hor... U c already then say...
4         1  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567      0  This is the 2nd time we have tried 2 contact u...
5568      1               Will ü b going to esplanade fr home?
5569      1  Pity, * was in mood for that. So...any other s...
5570      1  The guy did some bitching but I acted like i'd...
5571      1                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [37]:
x=df.msg.values
y=df.status

In [38]:
x

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [39]:
y.dtype

dtype('O')

In [40]:
y.astype('int')

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: status, Length: 5572, dtype: int64

In [41]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1)

In [42]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
xtraincv=cv.fit_transform(xtrain)
xtestcv=cv.transform(xtest)

In [43]:
xtrain

array(["Hi , where are you? We're at  and they're not keen to go out i kind of am but feel i shouldn't so can we go out tomo, don't mind do you?",
       'If you r @ home then come down within 5 min',
       "When're you guys getting back? G said you were thinking about not staying for mcr",
       ...,
       'CERI U REBEL! SWEET DREAMZ ME LITTLE BUDDY!! C YA 2MORO! WHO NEEDS BLOKES',
       'Text & meet someone sexy today. U can find a date or even flirt its up to U. Join 4 just 10p. REPLY with NAME & AGE eg Sam 25. 18 -msg recd@thirtyeight pence',
       'K k:) sms chat with me.'], dtype=object)

In [46]:
xtraincv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [48]:
ytrain,ytest=ytrain.astype('int'),ytest.astype('int')

In [49]:
from sklearn.naive_bayes import MultinomialNB
mnb=MultinomialNB()
mnb.fit(xtraincv,ytrain)

MultinomialNB()

In [50]:
mnb.score(xtraincv,ytrain)

0.9923715503702042

In [53]:
xtest[0]

'Yep, by the pretty sculpture'

In [58]:
ytest.iloc[0]

1

In [55]:
xtestcv[0].toarray()

array([[0, 0, 0, ..., 0, 0, 0]])

In [56]:
mnb.predict(xtestcv[0])

array([1])

In [61]:
ex="""Get welcome bonus of rs. 11,001"""
test=cv.transform([ex])
mnb.predict(test)

array([0])